version: '3'

services:
  sec_fmt:
    build: .
    volumes:
      - ./share:/home/sec_fmt:ro
      - ./xinetd:/etc/xinetd.d/sec_fmt:ro
    ports:
      - "10101:10101"
    expose:
      - "10101"
    restart: always
