version: '3'

services:
  colculatar:
    build: ./
    volumes:
      - ./share:/home/colculatar:ro
      - ./xinetd:/etc/xinetd.d/colculatar:ro
    ports:
      - "12345:12345"
    expose:
      - "12345"